Lecture 7
Letto228/Angular-learnjs-150523 pull request #112
Opened 2023-06-25 10:18 UTC by Germangami

2023-06-25 10:40 UTC, Letto228 reviewed
Привет
По логике и применению - все супер 👍 
Оставил комментарий по неймингу и функции `filterProduct`. Буду ждать от тебя ответов и после них - готов поставить аппрув

2023-06-25 10:40 UTC, Letto228 commented on src/app/shared/filter-by-product/filter-by-product.pipe.ts
> +@Pipe({name: 'filterByProduct'})
Почему `filterByProduct`? Из названия следует, что мы фильтруем по продуктам, но на самом деле происходит "фильтрация продуктов по имени" - `filterProductsByName`

2023-06-25 10:40 UTC, Letto228 commented on src/app/shared/filter-by-product/filter-by-product.ts
> +export function filterProduct(value: number | undefined | null, separator: string = '_') {
Рудимент?)

2023-06-25 10:40 UTC, Letto228 commented on src/app/shared/filter-by-product/filter-by-product.ts
> +export function filterProduct(value: number | undefined | null, separator: string = '_') {
Вроде нигде не используется

2023-06-25 10:56 UTC, Germangami commented on src/app/shared/filter-by-product/filter-by-product.ts
> +export function filterProduct(value: number | undefined | null, separator: string = '_') {
Ой) думал почистил, уже удаляю

2023-06-25 10:57 UTC, Germangami commented on src/app/shared/filter-by-product/filter-by-product.pipe.ts
> +@Pipe({name: 'filterByProduct'})
я походу понял, как нужно на хард моде сделать

2023-06-25 19:35 UTC, Letto228 requested changes
Да, очено похоже на правду - молодец!
Есть один недочет - оставил комментарий, посмотри, пожалуйста

2023-06-25 19:35 UTC, Letto228 commented on src/app/shared/filter-by-product/filter-by-product.pipe.ts
> +@Pipe({name: 'filterByProduct'})
Но поинт с неймингом все еще актуален)) плюс, если у тебя нет завязки на сущности продукта, то еще стоит и `product` из нейминга убрать?

2023-06-25 19:35 UTC, Letto228 commented on src/app/shared/filter-by-product/filter-by-product.pipe.ts
> +        if (typeof categoryName === 'string') {
А мы точно то проверяем на принадлежность к строковому типу? Кажется, что будем почти всегда в данный if попадать.

2023-06-26 06:41 UTC, Germangami commented on src/app/shared/filter-by-product/filter-by-product.pipe.ts
> +        if (typeof categoryName === 'string') {
Да, точно понял. Исправил

2023-07-02 08:38 UTC, Letto228 approved these changes
Огнище 🔥 - аппрув!

2023-07-02 08:38 UTC, closed without merging