Lecture 2
Letto228/Angular-learnjs-150523 pull request #30
Opened 2023-05-23 10:25 UTC by valeriiSkliar

2023-05-24 05:54 UTC, Letto228 requested changes
Привет!
Оставил пару комментариев: нужно чуть доделать функциональность, согласно ДЗ и проверить корректность работы стилей

Еще подмечу: обрати внимание, как схематики создали компонент, он у тебя лежит по пути `products-list/card/card`, согласись, по структуре - выглядит не очень. Файлы компонента стоит расположить в той же директории, что и модуль. Для этого есть 3 способа:
1. Самый не желательный - создать компонент и перетащить файлы вручную. Согласись, такое себе
2. Находясь в директории `products-list`, вызвать команду `npx ng g c card`. В таком случае, схематики `AngularCLI` создадут файлы компонента в директории `card`, то есть в той директории, где уже существует модуль (`CardModule`).
3. Находясь в директории `card`, вызвать команду `npx ng g c card --flat`. В таком случае, схематики `AngularCLI`, из-за флага `--flat`, создадут файлы компонент в той же директории, где была вызвана команда (`card`), то есть в той директории, где уже существует модуль (`CardModule`). Резюмируя, при помощи `--flat` мы говорим `AngularCLI`, что не нужно создавать отдельную директорию под файлы компонента

Сейчас самым простым решением будет воспользоваться первым пунктом, но на будущее - стоит использовать 2 или 3, чтобы меньше делать рутинной работы руками)

2023-05-24 05:54 UTC, Letto228 commented on src/styles.css
> +.test {
Осталось от теста? Если не используем, то стоит убрать

2023-05-24 05:54 UTC, Letto228 commented on src/app/pages/products-list/card/card/card.component.html
> +        <button mat-button>BUY</button>
По условию ДЗ нужно было остановить всплытие события клика по кнопке. У тебя данной функциональности я не увидел

2023-05-24 05:54 UTC, Letto228 commented on src/app/pages/products-list/card/card/card.component.css
> +    width: 35%;
Есть не большие сомнения по стилям 🤔
Ты пробовал вставить данный компонент на страницу и задать ему четкий размер?
Пример:

products-list.component.html
```html
<app-card class="card">
```

products-list.component.html
```css
.card {
    display: flex; // or display: block;
    height: 200px;
    width: 100px;
}
```

Предполагаю, что в таком случае, размеры, что ты указал у класса `example-card`, немного нам не подойдут, ведь высота будет считаться от контейнера элемента, то есть от `хост-элемента` (`<app-card>`) - `(200 * 0.5)px` (`100px` вместо `200px`)

2023-05-24 08:27 UTC, valeriiSkliar commented on src/app/pages/products-list/card/card/card.component.css
> +    width: 35%;
Действительно хотел задать размеры элементу, но не уделил должного внимания работе со стилями. На будущее учту.

2023-05-24 08:28 UTC, valeriiSkliar commented on src/app/pages/products-list/card/card/card.component.html
> +        <button mat-button>BUY</button>
Исправил.

2023-05-24 08:28 UTC, valeriiSkliar commented on src/styles.css
> +.test {
Исправил.

2023-05-25 05:50 UTC, Letto228 approved these changes
Супер! Все изменения увидел - аппрув

2023-05-25 05:50 UTC, closed without merging