feat: added product card component
Letto228/Angular-learnjs-150523 pull request #36
Opened 2023-05-24 22:01 UTC by Resaw-git

2023-05-25 05:41 UTC, Letto228 requested changes
Привет!
Заданием было - "создать компонент карточки товара", но у тебя его нет( А мы под него даже модуль выделили.
Давай весь шаблон, что ты описал, и стили вынесем в отдельный компонент (`CardComponent` в директории `card`). Если же ты специально не стал выносить и есть причины так не делать, то напиши свои мысли, пожалуйста, или, если не понятно, почему так нужно делать, тогда уже я отпишу свои мысли по данному вопросу.

2023-05-25 05:41 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +        <img src="{{ product.images[0].url }}" alt="картинка товара" class="image" />
Почему тут решил использовать интерполяцию?

2023-05-25 05:41 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.ts
> +    onClick(e: Event) {
Подсвечу момент по хорошим практикам
Нейминг `e` я бы не назвал "хорошим", в целом сокращения не являются хорошими практиками при написании "чистого кода". Исключениями могут быть, общепринятые сокращения или аббревиатуры, и то, не всегда общепринятые сокращения хорошо читаются (получается, есть исключения среди исключений))

2023-05-25 10:38 UTC, Resaw-git commented on src/app/pages/products-list/products-list.component.html
> +        <img src="{{ product.images[0].url }}" alt="картинка товара" class="image" />
[src]= я так понял используется для привязки объектов, интерполяция для строк.
В react(jsx) похожий синтаксис для вставки значений в html, написал на автомате)

2023-05-25 10:40 UTC, Resaw-git commented on src/app/pages/products-list/products-list.component.ts
> +    onClick(e: Event) {
верно, иногда можно перепутать event и error если одной буквой называть, спасибо)

2023-05-27 09:24 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +        <img src="{{ product.images[0].url }}" alt="картинка товара" class="image" />
На лекции обсуждали иную стратегию))
Я рекомендовал подход:
- binding для передачи значения в свойство `HTMLElement` (будь то страка или объект)
- interpolation для вычисления значения в шаблон (контент)

Такой подход позволит держать шаблон в консистентном состоянии, соответсвенно, его будет проще читать: видим binding и сразу понимаем, что значение куда-то передается; видим interpolation - сразу понимаем, что вычисляемое значение отображается в шаблоне (странице)

2023-05-27 09:29 UTC, Letto228 approved these changes
Карточку увидел - все гуд, аппрув!
Отписался по поводу binding и interpolation, обрати внимание, пожалуйста

2023-05-27 09:31 UTC, closed without merging