feat: add card component | lecture-2 Homework
Letto228/Angular-learnjs-150523 pull request #39
Opened 2023-05-25 14:00 UTC by Blake-In-Town

2023-05-27 08:35 UTC, Letto228 requested changes
Нихао
Есть небольшой общий вопрос к компоненту карточки: он должен отображать данные, в нашем случае из мока (`productMock`), но в твое реализации `title`, `subtitle`, `avatar`, `content` отображаются статично в шаблоне, то есть, если мы поменяем мокомвые данные, то карточка станет не актуальна - она корректно отобразит только `img`. Согласись, не совсем то, что ожидалось
Оставил так же маленький комментарий к интерполяции в шаблоне, посмотри, пожалуйста

Буду очень ждать фидбека!

2023-05-27 08:35 UTC, Letto228 commented on src/app/pages/products-list/card/components/card/card.component.html
> +    <img mat-card-image alt="previewImg-{{ productMock._id }}" [src]="previewImg.src" />
Почему решил использовать interpolation? `eslint` ошибку подсветил при использовании binding?

2023-05-28 16:28 UTC, Blake-In-Town commented on src/app/pages/products-list/card/components/card/card.component.html
> +    <img mat-card-image alt="previewImg-{{ productMock._id }}" [src]="previewImg.src" />
Да, решил с ним не спорить, но и оставить подсказку, на случай отвала картинки

2023-05-28 16:42 UTC, Blake-In-Town commented
Я не промотал до конца mock файла, и не увидел что там ещё есть свойства. Поправил, прогнал через линт

2023-05-29 05:39 UTC, Letto228 commented on src/app/pages/products-list/card/components/card/card.component.html
> +    <img mat-card-image alt="previewImg-{{ productMock._id }}" [src]="previewImg.src" />
Он как раз и ругался на отсутствие `alt` при синтаксисе `[alt]`, видимо не умеет такое парсить)
Отключим на лекции данное правило

2023-05-29 05:45 UTC, Letto228 approved these changes
Супер!
Оставил пару рекомендательных комментариев: чуть не подчистил стили и 2 раза имя вывел) Но в остальном вопросов нет - аппрув!

Подмечу по поводу линтинга.
Ты написал, что все файлы прогнал через линтер, но делать это отдельно - в этом нет необходимости: мы настроили автоматический запуск линтинга при совершении коммита (`lint-staged` + `husky`). По этому, если смог закоммитить файлы - линтинг прошел успешно. НО молодец, что держишь руку на пульсе и следишь за качеством кода👍

2023-05-29 05:45 UTC, Letto228 commented on src/app/pages/products-list/card/components/card/card.component.css
> +    background-image: url('https://c.dns-shop.ru/thumb/st1/fit/0/0/dff090e667cd39dd397678905df52de5/6c3e7aab802deb19513c7cf55dd7c527efb9127d8aba2ed90f3d224577137fe2.jpg');
А вот тут у нас осталась статичная привязка(

2023-05-29 05:45 UTC, Letto228 commented on src/app/pages/products-list/card/components/card/card.component.html
> +            {{ productMock.name }}
Лучше бы в таком случае убрать `mat-card-subtitle`, думаю пользователю не совсем будет понятно, зачем 2 имени выводить 😅

2023-05-29 05:46 UTC, closed without merging

2023-05-29 08:04 UTC, Blake-In-Town commented on src/app/pages/products-list/card/components/card/card.component.css
> +    background-image: url('https://c.dns-shop.ru/thumb/st1/fit/0/0/dff090e667cd39dd397678905df52de5/6c3e7aab802deb19513c7cf55dd7c527efb9127d8aba2ed90f3d224577137fe2.jpg');
Принял, уберу

2023-05-29 08:05 UTC, Blake-In-Town commented on src/app/pages/products-list/card/components/card/card.component.html
> +            {{ productMock.name }}
Ну это заглушка, поскольку в моке не было своего свойства под subttitle