feat: add structural directive
Letto228/Angular-learnjs-150523 pull request #74
Opened 2023-06-04 18:00 UTC by divnvp

2023-06-04 18:01 UTC, divnvp commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +        setTimeout(() => {
Так и не смогла понять, как организовать логику так, чтобы вызывался только 1 метод sendLoadData при достижении цели, а не по 20 штук одновременно

2023-06-06 21:44 UTC, Letto228 requested changes
Привет
Увидел твой комментарий, возможно, я разгадал тайну) Оставил комментарии с вопросами и рассуждениями своими, посмотри, пожалуйста. Буду ждать ответов!

2023-06-06 21:44 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +    private readonly destroy$ = new Subject<void>();
А нам тут нужен `destroy$`?

2023-06-06 21:44 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +        setTimeout(() => {
Увидел твой комментарий и добавли в свое ДЗ решение, подумал, что такую логику можно было бы организовать отслеживаю вход и выход в зону отступа (`offset`).
Но, кажется, универсального решения тут нет, все зависит от целевой логики компонента, возможно, это нормально, что он столько событий прокидывает, а возможно, отправка событий будет регулироваться состоянием загруженности сверху или снизу: допустим, сверху не все данные загружены - значит можно отправить событие, после чего статус меняется на "загружаем" (`loading`), и при данном статусе запрещается отправка события из директивы, т.к. нет смысла запрашивать данные, пока не отработал предыдущий запрос

2023-06-06 21:44 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +        setTimeout(() => {
Твой вариант тоже подхдит, такая логика вполне может быть. Правда, стоит проработать граничные кейсы. Например, когда контейнер маленький и ты скролиш вверх, а потом резко вниз. В таком случае, событие загрузки сверху не отправится

Но ты пишешь, что не получилось не отправлять множество событий, что странно - вроде у тебя метод не должен вызываться по нескольку раз, т.к. стоит `setTimeout` и `clearTimeout`. Или я чего-то упускаю🤔

2023-06-06 21:44 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +        setTimeout(() => {
Кажется, нашел))
Подскажи, а `timeoutID` свойство точно `readonly`?
Ты не записываешь id таймера в свойство `timeoutID`, по этому он у тебя и не останавливается, в следствии чего все поставленные через `setTimeout` таски вызываются через 500мс и наблюдаем вызовы нескольких методов `sendLoadData`

Попробуй сделать стартовое состояние `timeoutID` === `null`, а в будущем - записывать в него id таймера возвращаемого из `setTimeout`. И при отработке `setTimout` нужно сбрасывать `timeoutID`

2023-06-06 21:44 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +            if (this.isTop(event.scrollTop)) {
Такой вопрос: получается, если мы начнем скролить от верхней границы вниз, то будет лететь событие о необходимости загрузки данных сверху? Предполагаю так, потому что направление скролла не учитывается

2023-06-07 06:49 UTC, divnvp commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +            if (this.isTop(event.scrollTop)) {
Этого не происходит сейчас из-за таймаута

2023-06-07 06:50 UTC, divnvp commented
Починилось, спасибо! Нужно быть внимательнее :) Теперь отправляется только по одному запросу и когда нужно

2023-06-09 07:14 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +            if (this.isTop(event.scrollTop)) {
Кажется, что есть все таки пограничные кейсы, например, когда проскролили чуть-чуть вниз, допустим на 20px от самой верхней позиции - находимся в пределах скролла, таймер отработал, значит выкинули событие в Output о загрузке данных сверху, но, кажется, так не должно быть

2023-06-09 07:16 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +            if (this.isTop(event.scrollTop)) {
Конечно, кейс минорный, но на проде такое вполне могло бы выстрелить

2023-06-11 14:56 UTC, Letto228 approved these changes
Бонжур!
Оставил комментарий по поводу проверки направления скролла, обрати внимание, пожалуйста - https://github.com/Letto228/Angular-learnjs-150523/pull/74/files#r1223932935

В остальном - хорошая директива получилась 👍 - аппрув!

2023-06-11 14:56 UTC, closed without merging