feat: lecture-4 add popup-host component
Letto228/Angular-learnjs-150523 pull request #75
Opened 2023-06-04 21:16 UTC by Germangami

2023-06-06 21:00 UTC, Letto228 requested changes
Привет!
Оставил комментарий, предполагаю, что забыли один кейс учесть - получение `null`, и нужно доработать директиву. Буду ждать от тебя фидбека по данному поводу

2023-06-06 21:00 UTC, Letto228 commented on src/app/components/popup/popup-host.component.ts
> +        this.viewPort.createEmbeddedView(this.template);
А проверял на данном примере: `<app-popup-host [template]="!closeTemplate ? first : null"></app-popup-host>`?
Видится, что при таком примере - будут ошибки

2023-06-06 21:00 UTC, Letto228 commented on src/app/components/popup/popup-host.component.ts
> +        if (template) {
Молодец, что проверил изменение инпута 👍

2023-06-12 20:21 UTC, Germangami commented on src/app/components/popup/popup-host.component.ts
> +        this.viewPort.createEmbeddedView(this.template);
не до конца понимаю, что тут нужно сделать и как проверить

2023-06-13 07:29 UTC, Letto228 commented on src/app/components/popup/popup-host.component.ts
> +        this.viewPort.createEmbeddedView(this.template);
У нас в данном ДЗ, в шаблоне `AppComponent` есть 2 примера, чтобы отследить правильность работы `popup-host`:
```ts
<!-- Switch template -->
<!-- <app-popup-host [template]="switchTemplate ? first : second"></app-popup-host> -->
<!-- or -->
<!-- Close template -->
<!-- <app-popup-host [template]="!closeTemplate ? first : null"></app-popup-host> -->
```
Соответсвенно, реализация компонента должна быть такова, чтобы корректно работал пример `Switch template` и `Close template`. Если включить пример `Close template`, то в твоем компоненте все будет не так гладко. Попробуй в том числе подправить типизацию: из примера `Close template` следует, что в инпут `template` у `PopupHostComponent` может передаваться не только `TmplateRef`, но и `null`. Как только ты обновишь типизацию, TS должен подсветить тебе ошибку с методом `createEmbeddedView`

2023-06-14 16:41 UTC, Germangami commented on src/app/components/popup/popup-host.component.ts
> +        this.viewPort.createEmbeddedView(this.template);
Готово :) надеюсь правильно понял

2023-06-14 18:07 UTC, Letto228 reviewed
Да, очень близко 👍 , оставил еще наводящий комментарий, посмотри, пожалуйста

2023-06-14 18:07 UTC, Letto228 commented on src/app/components/popup/popup-host.component.ts
> +        if (this.template) {
А как у тебя попап отображается? По коду, кажется, он у тебя открывается и никогда не закрывается, а по примеру, он должен открытся, через 3 сек скрыться и еще через 3 сек снова открыться

2023-06-14 22:25 UTC, Germangami commented on src/app/components/popup/popup-host.component.ts
> +        if (this.template) {
Да, он открывался и не закрывался. Теперь все работает, спасибо!

2023-06-15 05:43 UTC, Letto228 approved these changes
Отлично! - аппрув
Оставил микрокомментарий по улучшению качества кода

2023-06-15 05:43 UTC, Letto228 commented on src/app/components/popup/popup-host.component.ts
> +            this.viewPort.clear();
Можно разгрузить код вынеся общую часть перед `if`

2023-06-15 05:43 UTC, closed without merging

2023-06-15 07:22 UTC, Germangami commented on src/app/components/popup/popup-host.component.ts
> +            this.viewPort.clear();
Да точно, благодарю)