build(lecture-5): homework
Letto228/Angular-learnjs-150523 pull request #77
Opened 2023-06-05 13:45 UTC by architects1

2023-06-06 21:09 UTC, Letto228 requested changes
Привет
Есть пару вопросов по МР, посмотри, пожалуйста. Буду ждать фидбека!

2023-06-06 21:09 UTC, Letto228 commented on src/app/shared/scrollWithLoading/direction.enum.ts
> +export enum DirectionEnum {
Огонь, что вынес в отдельный файл 👍

2023-06-06 21:09 UTC, Letto228 commented on src/app/shared/scrollWithLoading/scroll-with-loading.directive.ts
> +        if (target.scrollTop < this.offsetLength) {
Такой вопрос: получается, если мы начнем скролить от верхней границы вниз, то будет лететь событие о необходимости загрузки данных сверху?

Еще подкину вопрос: а если контейнер с маленьким скролом, получется события будут сразу отправляться и на загрузку сверху и на загрузку снизу?

2023-06-07 04:34 UTC, architects1 commented on src/app/shared/scrollWithLoading/scroll-with-loading.directive.ts
> +        if (target.scrollTop < this.offsetLength) {
Надо было дописать проверку куда идёт скрол в каждом if

Так что да, если сверху скролл небольшой сделали вниз и он попадает в условие верхнее, то отправляется событие

2023-06-09 07:24 UTC, Letto228 commented on src/app/shared/scrollWithLoading/scroll-with-loading.directive.ts
> +        if (target.scrollTop < this.offsetLength) {
Давай тогда возьмем на вооружение данный комментарий, если такая задачка на работе появится - добавь проверку на направление скролла

2023-06-09 07:24 UTC, Letto228 approved these changes

2023-06-09 07:24 UTC, closed without merging