#lecture-6 / Added pagination directive
Letto228/Angular-learnjs-150523 pull request #79
Opened 2023-06-07 07:20 UTC by fuckomako

2023-06-07 07:22 UTC, fuckomako commented on src/app/pages/products-list/products-list.component.html
> +    <ng-container
Здесь долго плутал ибо есть много закомментированного кода, но разобрался)

2023-06-07 07:22 UTC, fuckomako commented on src/app/shared/pagination/pagination.directive.ts
> +    @Input() appPaginationChankSize = 4;
Жесткий линтер однако, ругается на каждый чих)

2023-06-09 07:25 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +    @Input() appPaginationChankSize = 4;
Зато код чистый))

2023-06-09 07:33 UTC, Letto228 requested changes
Привет!
Круто 👍, оставил пару комментариев, посмотри, пожалуйста. Буду ждать твоего фидбека!

2023-06-09 07:33 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +    <ng-container
Молодец, что разобрался 👍

2023-06-09 07:33 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +        <div class="pagination-container">
Интересное решение - вставить пагинацию сверзу)

2023-06-09 07:33 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +                [ngClass]="{current: page === index}"
Я бы рекомендовал для таких конструкций использовать binding класса: `[class.current]="page === index"`

2023-06-09 07:33 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +        this.totalPages = this.appPaginationOf
Не корректно высчитывать данное значение в `OnInit`, т.к. если у тебя поменяется длинна входного массива, то `totalPages` не пересчитается, ведь `ngOnInit` вызывается только один раз

2023-06-09 07:33 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +            pages: [...new Array(this.totalPages).keys()],
Тогда, быть может `new Array(this.totalPages).keys()`? Не совсем понимаю необходимость в `[...new Array]`

2023-06-09 07:33 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +    private getPage(page: number) {
А давай над неймингом подумаем, разве метод `getPage` возвращает страницу? Кажется, что нет, он **устанавливает** выбранную страницу, т.е. ему больше подходит имя `setPage` или `setCurrentPage`. Что думаешь?

2023-06-09 08:17 UTC, fuckomako commented on src/app/pages/products-list/products-list.component.html
> +        <div class="pagination-container">
Да, я как то не особо заморачивался))
Не думаю что это критично)

2023-06-09 08:17 UTC, fuckomako commented on src/app/pages/products-list/products-list.component.html
> +                [ngClass]="{current: page === index}"
понял - принял 👍

2023-06-09 08:19 UTC, fuckomako commented on src/app/shared/pagination/pagination.directive.ts
> +        this.totalPages = this.appPaginationOf
Хм, подумаю тогда еще!
Ага я проморгал что `ngOnInit` - один раз(

2023-06-09 08:19 UTC, fuckomako commented on src/app/shared/pagination/pagination.directive.ts
> +            pages: [...new Array(this.totalPages).keys()],
Здесь линтер ругался...
Я подумаю еще)

2023-06-09 08:20 UTC, fuckomako commented on src/app/shared/pagination/pagination.directive.ts
> +    private getPage(page: number) {
`Дельное замечание` 👍

2023-06-09 09:02 UTC, fuckomako commented on src/app/pages/products-list/products-list.component.html
> +                [ngClass]="{current: page === index}"
ты же мне писал уже подобное в предыдущем реквесте!

2023-06-11 15:06 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +                [ngClass]="{current: page === index}"
Возможно, подзабылось, кому писал, а кому нет, решил, что лучше лишний раз подсветить, чем оставить без внимания)

2023-06-11 15:15 UTC, Letto228 reviewed
Правки увидел - все гуд, остался один вопрос по поводу `OnInit`: https://github.com/Letto228/Angular-learnjs-150523/pull/79#discussion_r1223947078. Подскажи, по нему ждать правок?

2023-06-13 07:49 UTC, fuckomako commented
> Правки увидел - все гуд, остался один вопрос по поводу `OnInit`: [#79 (comment)](https://github.com/Letto228/Angular-learnjs-150523/pull/79#discussion_r1223947078). Подскажи, по нему ждать правок?

Ой, извини забыл перенести в `ngOnChanges` - да я это пофикшу 👍

2023-06-13 18:18 UTC, Letto228 requested changes
Ух, давай подсоберемся и добьем это ДЗ. Оставил пару комментариев по удалению `ngOnInit`. Спойлер - не все так гладко получилось(

2023-06-13 18:18 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
>          this.listenCurrentIndexChange();
А как думешь данный метод должен вызываться на каждое изменение инпутов, это же сколько подписок у нас создастся и все они будут очищать и создавать view, прикинь, сколько лишней работы...

2023-06-13 18:18 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +        this.totalPages = this.appPaginationOf
Мне кажется, что массивы нужно посчитать перед вызовом метода `updateView`?🤔

2023-07-02 09:43 UTC, Letto228 commented
Привет!
Мр давно висит без изменений - закрою его. Если захочется внести правки и чтобы я провел ревью - просто переоткрой МР и напиши мне в Discord)

2023-07-02 09:43 UTC, closed without merging