build(lecture-6): homework
Letto228/Angular-learnjs-150523 pull request #91
Opened 2023-06-11 13:43 UTC by architects1

2023-06-11 13:52 UTC, architects1 commented
Решил ещё добавить в директиву управлением количества чанков

2023-06-13 17:45 UTC, Letto228 requested changes
Привет!
Как то много комментариев набежало в этот раз, прочитай внимательно, пожалуйста. При необходимости - договоримся о дополнительном созвоне, чтобы пройтись по МР и обсудить все моменты, только напиши мне в дискорде, чтобы мы время подобрали

2023-06-13 17:45 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +    *appPagination="
Почему решил `*appPagination` расположить выше `*ngIf` проверяющего наличие массива и показывающего лоадер?

В моем понимании, выгодней для начала проверить наличие массива, и только потом дробить его на подмассивы

2023-06-13 17:45 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +    <div *ngIf="currentItems?.length; else loader" class="scroll-container">
Почему решил проверять длину массива (`currentItems?.length`)?

Я считаю, что это не совсем корректный показатель загрузки. Допустим, бэкенд отдает нам пустой массив с продуктами, получется данные мы получили, но они пустые, тогда почему мы показываем пользователю лоадер? Мол данные все еще загружаются. Кажется, пользовательский опыт от этого пострадает, начнутся звонки в поддержку, а ля "почему у меня не загружаются продукты?"
Резюмируя: рекомендую показывать отдеьное состояние для пустого массива, если очень хочется, или пустую страницу, на крайний случай, но не лоадер, вводящий пользователя в заблуждение

2023-06-13 17:45 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +            this.appPaginationChunkSize = this.chunkSizes[chunkSizeIndex];
А что тут у нас такое?) Изменение инпут свойства из класса компонента🤔

2023-06-13 17:45 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +                (click)="setChunkSize(i)"
`setChunkSize` - это не корректное поведение

Вспомни первые наши лекции, когда мы только начинали говорить про инпуты и когда создавали sidenav компонент. У тебя есть инпут `appPaginationChunkSize`, который говорит о том, какой размернности должен быть чанк, по этому, размеренность чанка ты должен регулировать через данный инпут, т.е. если ты хочешь поменять размер, то передай в данный инпут новое значение.
Либо, убери возможность диктовать размеренность чанка родителем и сделай это внутренней логикой директивы.

А сейчас у нас путаница вышла, то ли через инпут диктуем размернность чанка, то ли через директиву

2023-06-13 17:45 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +                (click)="setChunkSize(i)"
Возможно, не совсем понятно отписал, если вопросы при прочтении возникли - обязатеьно пиши, какие, напишу более развернуто с упором на них

2023-06-13 17:45 UTC, Letto228 commented on src/app/shared/pagination/pagination-context.interface.ts
> +    $implicit: T[] | null | undefined;
Это судя по всему последствия замены местами `*appPagination` и `*ngIf`

2023-06-13 17:45 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +                (click)="setChunkSize(i)"
И я бы передавал размер чанка, так более прозрачно получается - `setChankSize(size)`

2023-06-13 17:45 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +    readonly chunkSizes: number[] = [4, 8, 12, 16, 20];
`private`?

2023-06-13 17:45 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +    readonly chunkSizes: number[] = [4, 8, 12, 16, 20];
Я бы рекомендовал данный массив вынести в константу, а не хранить его в свойстве класса

2023-06-13 17:45 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +        this.changeDetectorRef.markForCheck();
Зачем тут `markForCheck`?

2023-06-13 17:45 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +        this.viewContainer.createEmbeddedView(this.template, this.getCurrentContext());
Зачем тут создаешь view?

2023-06-13 17:45 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +        if (!this.appPaginationOf || !this.appPaginationOf?.length) {
Может данную проверку стоит вынести на уровень выше, таким образом получится избежать копипасты в методах:
```ts
ngOnChanges({appPaginationOf, appPaginationChunkSize}: SimpleChanges) {
        if (appPaginationOf || appPaginationChunkSize) {
            if (!this.appPaginationOf || !this.appPaginationOf?.length) {
                return;
            }

             this.setPages();
             this.setCurrentItems();
        }
}
```

Как уменьшить вложенность блоков я бы еще подумал, наверное метод бы отдельный создал

2023-06-13 17:45 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +        this.pages = [];
Лучше собрать массив в отдельной чистой функции и передать его в свойство `pages`, нежели присвоить пустой массив и начать его заполнять. Т.к. сборку массива можно вынести в отдельную функцию, как и написал выше, и сделать код более читаемым: `this.pages = getPagesBySize()`

2023-06-13 17:45 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +            this.appPaginationChunkSize * (this.currentPage - 1),
Очень странно, почему мы делаем шаг назад от выбранной страницы для того, чтобы получить пачку по данной странице?

2023-06-14 16:47 UTC, architects1 commented on src/app/shared/pagination/pagination.directive.ts
> +        if (!this.appPaginationOf || !this.appPaginationOf?.length) {
Да, логично, в следующем коммите поправлю

2023-06-14 16:56 UTC, architects1 commented on src/app/pages/products-list/products-list.component.html
> +    *appPagination="
В изначальной верстке было так - 
```
<ng-container *appPagination="let chank of productsFromContext; chankSize: 4">
<div  *ngIf="getFilteredProducts as productsFromNgIf; else loader" class="scroll-container">
</div>
</ng-container>
```
думал что именно в такой последовательности и нужно делать, 
Поменяю

2023-06-14 16:58 UTC, architects1 commented on src/app/pages/products-list/products-list.component.html
> +    <div *ngIf="currentItems?.length; else loader" class="scroll-container">
Так как по умолчанию у меня стоят пустой массив в currentItems, то из-за этого всегда до else никогда не доходило

Так как я не знал, что можно делать не как в изначальной верстке, то сейчас проверял бы на products

2023-06-14 17:04 UTC, architects1 commented on src/app/pages/products-list/products-list.component.html
> +                (click)="setChunkSize(i)"
Понял, переделаю

Изначально хотел что бы через инпут могли задать размер чанка только из заранее существующих размеров. Корректно бы было такое сделать через enum и принимать в appPaginationChunkSize только значения данного enum?

2023-06-14 18:10 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +                (click)="setChunkSize(i)"
Да, все верно говоришь!
Если тебе хочется устанавливать только фиксированные значения, то делать это лучше через `enum`

2023-06-18 13:54 UTC, architects1 commented on src/app/shared/pagination/pagination.directive.ts
> +            this.appPaginationChunkSize = this.chunkSizes[chunkSizeIndex];
Забыл что так нельзя
В следующем коммите поменяю appPaginationChunkSize на сеттер и добавлю локальную переменную

2023-06-18 13:57 UTC, architects1 commented on src/app/shared/pagination/pagination-context.interface.ts
> +    $implicit: T[] | null | undefined;
То что $implicit может быть null или undefined?

2023-06-18 14:03 UTC, architects1 commented on src/app/shared/pagination/pagination.directive.ts
> +        this.viewContainer.createEmbeddedView(this.template, this.getCurrentContext());
Из-за того что криво написал код, это был костыль для показания лоадера
Всё из-за того что товары текущие пустые, а если так, то метод updateView не вызывался в setCurrentItems, в следствии чего не создавался view

2023-06-18 14:03 UTC, architects1 commented on src/app/shared/pagination/pagination.directive.ts
> +        this.changeDetectorRef.markForCheck();
Вставил по ошибке

2023-06-18 14:56 UTC, architects1 commented on src/app/shared/pagination/pagination.directive.ts
> +            this.appPaginationChunkSize * (this.currentPage - 1),
Потому что по факту currentPage значит именно страницу, а не индекс чанка продуктов

К примеру, если всего товаров у нас 5 и длина чанков  2 и их поделить на массивы, то у нас получится :

[
  [prod,prod],  - индекс 0, номер страницы 1
  [prod,prod], - индекс 1, номер страницы 2
  [prod],  индекс 2, номер страницы 3
]

В моём решение я не стал сразу резать товары на чанки, а решил резать оригинальный массив в зависимости от страницы. Мне нужно резать по индексу умноженный на кол-во товаров в чанке до следующего индекса, но так как у меня сохраняется номер страницы, а не индекс, то я вычитаю 1, так индекс всегда меньше номера страницы на 1.

2023-06-19 09:32 UTC, architects1 commented
Запушил новый коммит, случайно в сообщении номер лекции указан неверно

2023-06-25 08:04 UTC, Letto228 commented on src/app/shared/pagination/pagination-context.interface.ts
> +    $implicit: T[] | null | undefined;
Yep

2023-06-25 08:09 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +            this.appPaginationChunkSize * (this.currentPage - 1),
Смотри, хороший поинт нашли, где код не совсем прозрачный, просто сам факт, что для получения текущего - делаем шаг назад, для меня показался странным. Но, вот если бы ты пометил, что это высчитывается индекс чанка - вопрос бы сразу отпал и код был бы прозрачней. Для этого есть 2 способа:
1. Можно оставить комментарий и в нем рассказать что происходит. Но данный способ мне совершенно не нравится
2. Самокомментируемый код. Простым выносом константы с `this.currentPage - 1` мы бы решили все проблемы:
```ts
const chankIndex = this.currentPage - 1;

this.currentItems = this.appPaginationOf.slice(
            this.appPaginationChunkSize * (chankIndex),
            ...
```

2023-06-25 08:11 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +            this.appPaginationChunkSize * (this.currentPage - 1),
В том числе и тебе через пару месяцев или даже лет, не придется вспоминать, что тут такое. Возможно для тебя поинт покажется надуманным и раздутым, но по моему опыту - проблема очень актуальна, даже на таких мелочах

2023-06-25 08:19 UTC, Letto228 approved these changes
Привет!
Оставил парочку рекомендательных комментариев по чистоте кода, в остальном все гуд 👍 - аппрув

2023-06-25 08:19 UTC, Letto228 commented on src/app/shared/pagination/pagination-context.interface.ts
> +    setChunkSize: (index: number) => void;
Я бы оставил что-то одно, либо `setChunkSize`, либо `setPage`

2023-06-25 08:19 UTC, Letto228 commented on src/app/shared/pagination/pagination-context.interface.ts
> +    setPage: (index: number) => void;
И тут в аргументе, мы передаем не `index`, а `page`?

2023-06-25 08:21 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +    @Input() set appPaginationChunkSize(number : 4 | 8 | 12 | 16 | 20 ) {
Я чуть подумал, мы могла бы еще в нейминге отразить, что в инпут передается initialValue - `appPaginationInitialChunkSize`. Это повысило бы прозрачность директивы

2023-06-25 08:23 UTC, closed without merging

2023-06-25 08:59 UTC, architects1 commented on src/app/shared/pagination/pagination.directive.ts
> +            this.appPaginationChunkSize * (this.currentPage - 1),
Стоило переменные получше назвать, что бы понятно сразу было