feat: lecture-5 add load scroll derective
Letto228/Angular-learnjs-150523 pull request #96
Opened 2023-06-12 20:15 UTC by Germangami

У меня проблемы,  если честно вообще не понял что и как тут делать, что-то такое вышло

2023-06-13 17:46 UTC, Letto228 commented
А в чем именно непонятки, что в ДЗ ввело в такое состояние?

2023-06-13 17:56 UTC, Letto228 requested changes
Привет!
Я оставил пару комментариев, посмотри, пожалуйста, возможно станет чуть понятней по ДЗ, понимаю, что большинство из комментариев возникли из-за непонимания.
Если вопросы остались и ДЗ все еще не понятно - напиши мне в личку в Discord, будем с тобой вместе искать истину)

2023-06-13 17:56 UTC, Letto228 commented on src/app/shared/load-scroll/load-scroll.directive.ts
> +        if (!this.eventSent) {
Получается, событие у нас отправится только один раз?

2023-06-13 17:56 UTC, Letto228 commented on src/app/shared/load-scroll/load-scroll.directive.ts
> +export enum LoadDirection {
Рекомендую вынести в отдельный файл, так и файл директивы будет чище и импорт к данному энаму будет прозрачней

2023-06-13 17:56 UTC, Letto228 commented on src/app/shared/load-scroll/load-scroll.directive.ts
> +    @Output() sentEvent = new EventEmitter<string>();
У тебя есть прекрасный `enum`, почему не стал его использовать для типизации `EventEmitter`?

2023-06-13 17:56 UTC, Letto228 commented on src/app/shared/load-scroll/load-scroll.directive.ts
> +        const scrollTop = target.scrollTop;
зачем константа выше? Можно просто достать сразу нужное свойство: `const scrollTop =(event.target as HTMLElement).scrollTop`

2023-06-13 17:56 UTC, Letto228 commented on src/app/shared/load-scroll/load-scroll.directive.ts
> +            if (scrollTop > 100) {
По условию требовалось отправлять событие загрузки сверху, если оступ сверху меньше `100px`, и отправлять событие загрузки снизу, если снизу отступ меньше `100px`. У тебя отступ снизу не проверяется, только сверху, к тому же условие совершенно обратное, если отступ больше `100px`, то отправляешь событие загрузки сверху, а если нет, то снизу. Предположительно, у тебя всегда отправляется событие загрузки снизу, после чего директива события отправлять не может, из-за проверки флага `eventSent`

2023-06-14 16:45 UTC, Germangami commented on src/app/shared/load-scroll/load-scroll.directive.ts
> +export enum LoadDirection {
Понял, сделано

2023-06-14 16:47 UTC, Germangami commented on src/app/shared/load-scroll/load-scroll.directive.ts
> +    @Output() sentEvent = new EventEmitter<string>();
И в самом деле глупо, исправлено

2023-06-14 22:09 UTC, Germangami commented on src/app/shared/load-scroll/load-scroll.directive.ts
> +            if (scrollTop > 100) {
т.е если я правильно понимаю, мы отскролили от верхней границы допустим на 200px и отправили событие scrollTop
а после снова вернулись на самый верх т.е scrollTop 0px и если мы снова опустимся на больше чем 100px нужно снова отправлять ивент?

2023-06-15 05:47 UTC, Letto228 commented on src/app/shared/load-scroll/load-scroll.directive.ts
> +            if (scrollTop > 100) {
Не, немного наоборот. Тебе нужно при ПРИБЛИЖЕНИИ к верхней/нижней границе отправить событие по загрузке данных. Что означает при приближении: когда до верхней/нижней границе остается меньше `N px`, т.е. если скроллим на верх и расстояние д верхней границы меньше `N px`, то отправляем событие, если расстояние до верхней границе больше `N px`, то событие не отправляем.

2023-06-15 05:50 UTC, Letto228 commented on src/app/shared/load-scroll/load-scroll.directive.ts
> +            if (scrollTop > 100) {
Давай с примером по нижней границе: ты скроллишь вниз, пока расстояние до нижней границы больше `N px`, то событие не отправляется; как только, при скролле вниз, расстояние до нижней границы станет меньше `N px` - отправляем событие загрузки

2023-06-15 05:56 UTC, Letto228 reviewed
Судя по коду, понял ты все верно, директива почти готова - 👍 
Оставил комментарий с предложениями по улучшению, посмотри, пожалуйста. Если у тебя есть вопросы или желание поправить - напиши, пожалуйста, МР пока закрывать не буду. Если нет ни вопросов ни желания поправить - тоже напиши, пожалуйста, я в таком случаи буду закрывать МР

2023-06-15 05:56 UTC, Letto228 commented on src/app/shared/load-scroll/load-scroll.directive.ts
> +        if (!this.eventTop && scrollTop <= 100) {
Рекомендую добавить в проверку направление скролла и выход из функции при попадании в один из `if`. Т.к., согласись, странно отправлять одновременно событие загрузки сверху и снизу и странно при скролле вверх отправлять событие загрузки снизу (такое возможно, если контейнер маленький и одновременно есть приближение при скролле к верхней и нижней границе одновременно)

2023-07-02 06:36 UTC, Letto228 commented
Привет!
Около 2х недель нет ответа, давай МР закрою, если захочешь доработать - просто переоткрой его с исправлением и я посмотрю

2023-07-02 06:36 UTC, closed without merging